variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CLIENT_TIMEOUT: 600
  COMPOSE_HTTP_TIMEOUT: 600
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0
  POSTGRES_DB: "test_db"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: "trust"
  DATABASE_URL: "postgresql://$POSTGRES_USER@postgres/$POSTGRES_DB"
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - venv/
    - .cache/pip
    - $DATA_DIRECTORY/

stages:
  - build
  - unit-test
  - security-scan
  - dependency-scan
  - deploy

build_job:
   stage: build
   image: docker:20.10.16
   services:
       - docker:20.10.16-dind
   script:
       - docker build -t ex-build-dev:latest .
   rules:
    - if: $CI_COMMIT_BRANCH == "main"

unit-test-job:
  stage: unit-test
  image: python:3.9-slim
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest app/tests/unit_tests/ --cov --cov-report=xml  # Testes unitários
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml  # Apenas um arquivo é permitido
    paths:
      - coverage.xml
      - htmlcov/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

bandit_scan:
  stage: security-scan
  image: python:3.9-slim
  before_script:
    - pip install --upgrade pip
    - pip install bandit
  script:
    - bandit -r app/ --exclude tests/ -f json -o bandit-report.json
  artifacts:
    when: always
    reports:
      sast: bandit-report.json
    paths:
      - bandit-report.json
    expire_in: 7 days
  allow_failure: true

dependency_check:
  stage: dependency-scan
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    NVD_API_KEY: "$NVD_API_KEY"
  before_script:
    - mkdir -p reports
  script:
    - docker run --rm 
      -v "$CI_PROJECT_DIR:/app" 
      -v "$CI_PROJECT_DIR/reports:/app/reports"
      -e JAVA_OPTS="-Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false --enable-preview"
      owasp/dependency-check:latest 
      dependency-check.sh 
      --scan /app 
      --format JSON 
      --out /app/reports 
      --project "task-manager-app" 
      --nvdApiKey "$NVD_API_KEY"
      --failOnCVSS 11
    - ls -la reports/
  artifacts:
    when: always
    paths:
      - reports/
    reports:
      dependency_scanning: reports/dependency-check-report.json
    expire_in: 7 days
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy_job:
    stage: deploy
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    before_script:
        - echo "Remove anterior"
        - PORT_CONTAINERS=$(docker ps --filter "publish=5000" -q)
        - echo $PORT_CONTAINERS
        - if [ -n "$PORT_CONTAINERS" ]; then
            docker stop $PORT_CONTAINERS;
            docker rm $PORT_CONTAINERS;
            sleep 5;
          fi
    script:
        - echo "Deploying the app"
        - docker run -d -p 5000:5000 ex-build-dev:latest
    rules:
       - if: $CI_COMMIT_BRANCH == "main"
