variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CLIENT_TIMEOUT: 600
  COMPOSE_HTTP_TIMEOUT: 600
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0
  POSTGRES_DB: "test_db"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: "trust"
  DATABASE_URL: "postgresql://$POSTGRES_USER@postgres/$POSTGRES_DB"


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - venv/
    - .cache/pip

stages:
  - build
  - unit-test
  - security-scan-bandit
  - deploy

build_job:
   stage: build
   image: docker:20.10.16
   services:
       - docker:20.10.16-dind
   script:
       - docker build -t ex-build-dev:latest .
   rules:
    - if: $CI_COMMIT_BRANCH == "main"

unit-test-job:
  stage: unit-test
  image: python:3.9-slim
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest app/tests/unit_tests/ --cov --cov-report=json  # Testes unitários
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

bandit_scan:
  stage: security-scan-bandit
  image: python:3.9-slim
  before_script:
    - pip install --upgrade pip
    - pip install bandit
  script:
    - bandit -r app/ --exclude tests/ -f json -o bandit-report.json
  artifacts:
    when: always
    reports:
      sast: bandit-report.json
    paths:
      - bandit-report.json
    expire_in: 7 days
  allow_failure: true

deploy_job:
    stage: deploy
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    before_script:
        - echo "Remove anterior"
        - PORT_CONTAINERS=$(docker ps --filter "publish=5000" -q)
        - echo $PORT_CONTAINERS
        - if [ -n "$PORT_CONTAINERS" ]; then
            docker stop $PORT_CONTAINERS;
            docker rm $PORT_CONTAINERS;
            sleep 5;
          fi
    script:
        - echo "Deploying the app"
        - docker run -d -p 5000:5000 ex-build-dev:latest
    rules:
       - if: $CI_COMMIT_BRANCH == "main"
